# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Under Review', max_length=50)),
                ('message_from_prof', models.CharField(max_length=500)),
                ('message_to_prof', models.CharField(max_length=500)),
                ('accept_status', models.CharField(default='Student Waiting', max_length=50)),
                ('accept_datetime', models.DateTimeField()),
                ('waitlist_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('ldap_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('additional_comments', models.CharField(max_length=1000)),
                ('requirements', models.CharField(max_length=1000)),
                ('num_positions', models.IntegerField(default=0)),
                ('application_deadline', models.DateField()),
                ('expected_start_date', models.DateField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('duration', models.IntegerField(default=0)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppa.Prof')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('ldap_id', models.CharField(max_length=50)),
                ('email', models.EmailField(default='dummy@email.com', max_length=100)),
                ('yos', models.CharField(default='0', max_length=2)),
                ('cpi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('ph_no', models.CharField(default='0000000000', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppa.Project'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppa.Student'),
        ),
    ]
