# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa', '0002_auto_20170602_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_dp',
            field=models.FileField(default='https://gymkhana.iitb.ac.in/~ugacademics/back.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='sop_question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
