# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppa', '0004_auto_20170706_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_dp',
        ),
    ]
