# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa', '0007_prof_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='profile_dp',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_dp',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
